import webbrowser
import pyautogui, sys
import time
songs = open("songs.txt", "r")
songslist = songs.readlines()
num_lines = sum(1 for line in open('songs.txt'))
for x in range(num_lines):
	webbrowser.open('http://youtube.com', new=2)
	pyautogui.moveTo(750, 125)
	time.sleep(5)
	pyautogui.click()
	pyautogui.write(str(songslist[x]))
	time.sleep(3)
	pyautogui.press('enter')
	time.sleep(3) 
	pyautogui.moveTo(730, 800)
	pyautogui.click(button='right')
	time.sleep(1)
	pyautogui.press('e')
	time.sleep(2)
	pyautogui.hotkey('ctrl', 'w')
	webbrowser.open('https://ytmp3.cc/en13/', new=2)
	pyautogui.moveTo(900, 350)
	time.sleep(3)
	pyautogui.click()
	time.sleep(2)
	pyautogui.hotkey('ctrl', 'v')
	time.sleep(3)
	pyautogui.press('enter') 
	time.sleep(3)
	pyautogui.moveTo(850, 350)
	pyautogui.click()
	time.sleep(3)
	pyautogui.hotkey('ctrl', 'w')
